# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - deploy
  - test
  - dependencyCheck

build:
  only:
    - schedules
  stage: build
  script:
    - ./gradlew clean
    - ./gradlew war

  artifacts:
    paths:
      - "build/libs/*.war"
    expire_in: 2 days

deploy:
  only:
    - schedules
  stage: deploy
  script:
    - ./gradlew rsyncExplodedWar

test:
  only:
    - schedules
  stage: test
  when: delayed
  start_in: 8 minutes
  script:
    - ./gradlew npminstalltest
    - ./gradlew rune2etest

dependencyCheck:
  stage: dependencyCheck
  only:
    - schedules
  script:
    - ./gradlew dependencyCheckAnalyze
  artifacts:
    name: "${CI_JOB_ID}_${CI_JOB_NAME}"
    when: always
    expire_in: 30 day
    paths:
      - build/reports/dependency-check-report.html